Repository ONSdigital/sdc-int-rh-ui, pull requests merged in 2022-11, with the labels that each got.

#70 Replace Welsh urls and remove Terms and Conditions link
  Makefile
  app/templates/base-cy.html
Labels: patch

#71 385 rh UI headers
  app/security.py
  tests/unit/test_app.py
Labels: feature

#73 Fix 508 replace welsh url
  app/config.py
  app/domains.py
  app/error_handlers.py
  app/handlers.py
  app/templates/base-cy.html
  app/templates/base-en.html
  app/templates/start-too-many-requests.html
  app/utils.py
  kubernetes/dev.yml
  tests/test_data/local.env
Labels: patch

#75 492 Fix RH UI local build image name
  Makefile
Labels: patch

#74 551 add welsh translations
  app/__init__.py
  app/handlers.py
  app/templates/base-en.html
  app/templates/cookies.html
  app/templates/privacy-and-data-protection.html
  app/templates/start.html
  app/translations/cy/LC_MESSAGES/messages.mo
  app/translations/cy/LC_MESSAGES/messages.po
  app/translations/en/LC_MESSAGES/messages.mo
  app/translations/en/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/utils.py
  babel.cfg
  tests/unit/__init__.py
  tests/unit/helpers.py
  tests/unit/test_eq.py
  tests/unit/test_handlers.py
  tests/unit/test_start_handlers.py
Labels: patch

#77 Catch Redis connection and unknown http errors
  .travis.yml
  app/app.py
  app/error_handlers.py
Labels: patch

#76 255 improve rh deactivated uac error message
  app/templates/start-uac-inactive.html
  app/translations/cy/LC_MESSAGES/messages.mo
  app/translations/cy/LC_MESSAGES/messages.po
  tests/unit/test_start_handlers.py
Labels: feature

#79 585 Fix prod config
  app/__init__.py
  app/app.py
  app/app_logging.py
  app/config.py
  app/constants.py
  app/domains.py
  app/eq.py
  app/error_handlers.py
  app/handlers.py
  app/i18n.py
  app/request.py
  app/rhsvc.py
  app/routes.py
  app/security.py
  app/session.py
  app/settings.py
  app/start_handlers.py
  app/trace.py
  docker/docker-compose-rh-ui.yml
  kubernetes/dev.yml
  tests/test_data/local.env
  tests/unit/helpers.py
  tests/unit/test_app.py
  tests/unit/test_eq.py
  tests/unit/test_handlers.py
  tests/unit/test_info.py
  tests/unit/test_start_handlers.py
Labels: bug, patch
